sáb 23 set 2023 00:32:58 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/sct b/sct
--- a/sct
+++ b/sct
@@ -23,20 +23,18 @@
 
 . lib.sh
 
-#declare -gA git_hosts=(
-declare -ga git_hosts=(
-	[manjaro]='https://gitlab.manjaro.org/applications'
-	[manjaro-community]='https://gitlab.manjaro.org/packages/community'
-	[manjaro-extra]='https://gitlab.manjaro.org/packages/extra'
-	[manjaro-kde-unstable]='https://gitlab.manjaro.org/packages/kde-unstable'
-	[manjaro-multilib]='https://gitlab.manjaro.org/packages/multilib'
-	[manjaro-core]='https://gitlab.manjaro.org/packages/core'
+declare -gA git_hosts=(
+	#	[manjaro]='https://gitlab.manjaro.org/applications'
+	#	[manjaro_community]='https://gitlab.manjaro.org/packages/community'
+	#	[manjaro_extra]='https://gitlab.manjaro.org/packages/extra'
+	#	[manjaro_kde_unstable]='https://gitlab.manjaro.org/packages/kde-unstable'
+	#	[manjaro_multilib]='https://gitlab.manjaro.org/packages/multilib'
+	#	[manjaro_core]='https://gitlab.manjaro.org/packages/core'
 	[aur]="https://aur.archlinux.org"
 	[biglinux]="https://github.com/biglinux"
 	[gitlab]="https://gitlab.archlinux.org/archlinux/packaging/packages"
 )
-#declare -g host_gitlab="https://gitlab.archlinux.org/archlinux/packaging/packages"
-#declare -g host_aur="https://aur.archlinux.org"
+declare -ga gitlab_deps
 
 getportpath() {
 	for repo in $PORT_REPO; do
@@ -128,7 +126,7 @@ get_depends() {
 	ppath=$(getportpath "$1") || return 0
 	sh_seek_script "$ppath"
 	deps=$(sed -n 's/^# depends[[:blank:]]*:[[:blank:]]*//p' "$ppath/$BUILD_SCRIPT" | awk '!a[$0]++' | tr '\n' ' ' | sed 's/,//g')
-#	[[ -z "$deps" ]] && source "$ppath/$BUILD_SCRIPT"
+	#	[[ -z "$deps" ]] && source "$ppath/$BUILD_SCRIPT"
 	source "$ppath/$BUILD_SCRIPT"
 	deps+=" ${depends[*]}"
 	depends="${depends[*]}"
@@ -497,18 +495,18 @@ sh_git_clone_pkg() {
 		# testar se diretório git
 		if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
 			log_msg "$(gettext "Repositório local encontrado : $path_pkgfullname")"
-#			log_msg "$(gettext "   Fazendo checkout...")"
-#			# Desfazer as alterações nos arquivos no repositório local
-#			if git checkout -- .; then
-				log_msg "$(gettext "   Atualizando repositório...")"
-				# --prune: Remove referências a branches remotos que foram excluídos no repositório remoto.
-				# Isso significa que, se um branch foi excluído no repositório remoto desde a última vez que você fez um fetch,
-				# ele será removido do seu repositório local.
-				if git fetch --all --prune; then
-					popd >/dev/null 2>&1
-					return 0
-				fi
-#			fi
+			#			log_msg "$(gettext "   Fazendo checkout...")"
+			#			# Desfazer as alterações nos arquivos no repositório local
+			#			if git checkout -- .; then
+			log_msg "$(gettext "   Atualizando repositório...")"
+			# --prune: Remove referências a branches remotos que foram excluídos no repositório remoto.
+			# Isso significa que, se um branch foi excluído no repositório remoto desde a última vez que você fez um fetch,
+			# ele será removido do seu repositório local.
+			if git fetch --all --prune; then
+				popd >/dev/null 2>&1
+				return 0
+			fi
+			#			fi
 			log_msg 1 "$(gettext "Falha enquanto atualizava repositório")"
 		fi
 		popd >/dev/null 2>&1
@@ -546,14 +544,12 @@ comment
 		log_msg "Procurando em: ${black}${irepo}${reset}"
 		if [[ $irepo == *aur* ]]; then
 			if response=$(git ls-remote --quiet ${irepo}/$pkgname.git) &&
-			[[ -n "$response" ]]
-			then
+				[[ -n "$response" ]]; then
 				lsearch=1
 			fi
 		else
 			if response=$(curl --insecure --compressed -s -w "%{http_code}\n" -o /dev/null -k --url ${irepo}/$pkgname.git) &&
-			[[ "$response" == "200" || "$response" == "301" || "$response" == "302" ]]
-			then
+				[[ "$response" == "200" || "$response" == "301" || "$response" == "302" ]]; then
 				lsearch=1
 			fi
 		fi
@@ -570,8 +566,61 @@ comment
 	return 1
 }
 
+# Função para limpar o nome das dependências
+clean_dependency_name() {
+	local dep_name="$1"
+	dep_name="${dep_name%%[<>=]*}" # Remove informações de versão
+	dep_name="${dep_name%%.so}"    # Remove extensão .so
+	[[ "$dep_name" = "sh" ]] && dep_name='bash'
+	echo "$dep_name"
+}
+
+function fetch_gitlab_deplist {
+	local ipkgs=("$1")
+	local path_pkgfullname="$SOURCE_DIR/$pkgname"
+	local ncount=0
+	local ntotal="${#ipkgs[@]}"
+
+	while ((ncount < ntotal)); do
+		package="${ipkgs[ncount]}"
+		((++ncount))
+
+		if sh_git_clone_pkg "$package"; then
+			pkgbuild_path="$path_pkgfullname/$package/PKGBUILD"
+
+			if [[ -e "$pkgbuild_path" ]]; then
+				# Use o comando `source` para carregar as variáveis do PKGBUILD
+				source "$pkgbuild_path"
+
+				for dependency in "${makedepends[@]}"; do
+					clean_dep_name="$(clean_dependency_name "$dependency")"
+
+					# Verifique se a dependência já existe no array ipkgs
+					dep_exists=false
+					for existing_dep in "${ipkgs[@]}"; do
+						if [[ "$existing_dep" == "$clean_dep_name" ]]; then
+							dep_exists=true
+							break
+						fi
+					done
+
+					# Se a dependência não existir, adicione-a
+					if [[ "$dep_exists" == false ]]; then
+						((++ntotal))
+						ipkgs+=("$clean_dep_name")
+						gitlab_deps+=("$clean_dep_name")
+					fi
+				done
+			fi
+		fi
+	done
+}
+
 scratch_build() {
+	#debug "$@"
 	export PKGNAME
+	export pkg
+
 	while [ "$1" ]; do
 		case "$1" in
 		-i | -u | -r | -g | -p) ;;
@@ -582,7 +631,6 @@ scratch_build() {
 			;;
 		--git=*)
 			GITLAB=1
-#			sh_add_git_source "${opt#*=}"
 			sh_add_git_source "${1#*=}"
 			;;
 		-*) OPTS="$OPTS $1" ;;
@@ -595,11 +643,10 @@ scratch_build() {
 		log_msg 1 "Please specify package(s) to build."
 		return 1
 	}
-	export pkg
 
 	if ((NODEPS)); then
 		INST=$PKGNAME
-#		sh_check_lockfile "$PKGNAME"
+		#		sh_check_lockfile "$PKGNAME"
 		if ((GITLAB)); then
 			if ! sh_git_clone_pkg $PKGNAME; then
 				log_msg 1 "Error ao clonar $PKGNAME"
@@ -608,12 +655,12 @@ scratch_build() {
 		fi
 	else
 		for i in ${PKGNAME[*]}; do
-#			sh_check_lockfile "$i"
+			#			sh_check_lockfile "$i"
 			if ((GITLAB)); then
-				if ! sh_git_clone_pkg $i; then
-					log_msg 1 "Error ao clonar $i"
-					return 1
-				fi
+				#				if ! sh_git_clone_pkg $i; then
+				#					log_msg 1 "Error ao clonar $i"
+				#					return 1
+				#				fi
 				IPKG="$IPKG $i"
 			else
 				if [ ! "$(getportpath "$i")" ]; then
@@ -625,15 +672,24 @@ scratch_build() {
 				fi
 			fi
 		done
-		[ "$IPKG" ] || return 0
+		[ "$IPKG" ] || {
+			log_msg 1 "Please specify package(s) to build."
+			return 1
+		}
 		log_msg "$(gettext "Resolvendo dependências...")"
-		INST="$(scratch_deplist -q "$IPKG $EXOPT")"
+		if ((GITLAB)); then
+			INST=("$PKGNAME ")
+			gitlab_deps=()
+			fetch_gitlab_deplist $IPKG
+			INST+=(${gitlab_deps[*]})
+		else
+			INST="$(scratch_deplist -q "$IPKG $EXOPT")"
+		fi
 	fi
 
+	#debug ${INST[*]}
+
 	if [ "$INST" ]; then
-
-#debug ${INST[*]}
-
 		for pkg in ${INST[*]}; do
 			ppath=$(getportpath "$pkg") || {
 				msg_portnotfound "$pkg"
